export class Fifaplayer {
    id:number;
    team_id:any
    short_name:string;
    long_name:string;
    age:number;
    dob:Date;
    nationality:string;
    height_cm:number;
    weight_kg:number;
    potential:number;
    value_eur:number;
    wage_eur:number;
    club:string;
    overall:number;
    player_positions:string;
    preferred_foot:string;
    weak_foot:number;
    skill_moves:number;
    international_reputation:number;
    work_rate:string;
    body_type: string;
    release_clause_eur:number;
    player_tags:string;
    team_position:string;
    team_jersey_number:number;
    joined:Date;
    loaned_from:string;
    contract_valid_until:number;
    nation_position:string;
    nation_jersey_number:number;
    pace:number;
    shooting:number;
    passing:number;
    dribbling:number;
    defending:number;
    player_traits:string;
    attacking_ratings:any[];
    mentality_ratings:any[];
    skill_ratings:any[];
    movement_ratings:any[];
    power_ratings:any[];
    def_ratings:any[];
    gk_ratings:any[]
    gk_skills:any[];
}